version: '3.8'

services:
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000

  redis:
    image: redis/redis-stack:latest
    container_name: practical02-rag-redis-1
    ports:
      - "6380:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data


volumes:
  chroma_data:
  redis_data: